# Generated by Django 4.1 on 2022-08-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_vase_alter_watering_options_alter_watering_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='vases',
            field=models.ManyToManyField(to='main_app.vase'),
        ),
    ]
